spring.application.name=blogger-management-system
logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.port=${PORT:8080}
jwt.secret=a8f9c2d4e6b1c3a5f7e9d0a2b4c6d8e0f1a3b5c7d9e2f4a6b8c0d2e4f6a8c1
spring.thymeleaf.check-template-location=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true